LOCAL_PATH := $(call my-dir)

CORE_DIR    := $(LOCAL_PATH)/..
SOURCE_DIR  := $(CORE_DIR)/src
INCLUDES    :=
SOURCES_C   :=
SOURCES_CXX :=

include $(CORE_DIR)/Makefile.common

COREFLAGS := -DANDROID -D__LIBRETRO__ -DHAVE_STRINGS_H -DRIGHTSHIFT_IS_SAR $(INCFLAGS)

include $(CLEAR_VARS)
LOCAL_MODULE    := retro
LOCAL_SRC_FILES := $(SOURCES_C)
LOCAL_CFLAGS    := $(COREFLAGS)
LOCAL_LDFLAGS   := -Wl,-version-script=$(CORE_DIR)/link.T
include $(BUILD_SHARED_LIBRARY)
