SOURCES_C += freeintv_libretro.c \
	intv.c \
	memory.c \
	cp1610.c \
	cart.c \
	controller.c \
	osd.c \
	psg.c \
	stic.c \
	deps/libretro-common/file/file_path.c \
	deps/libretro-common/compat/compat_strl.c \
	deps/libretro-common/compat/compat_strcasestr.c

SOURCES_CXX += 

INCLUDES += -Ideps/libretro-common/include